### ISSUE TITLE
Suggestion: no error if file / dir not found

### ISSUE THREAD

**Issue by PhiLhoSoft** [aleksei0807/remove-webpack-plugin#4]
I use your plugin to clean up directories (globally or for some files) before the build.
If the previous build failed (or if it is the first build), I see red errors, like:

> ./Project.API/Views/Home/favicon.ico: deleted ✖
> RemoveWebpackPlugin Error: ENOENT: no such file or directory, access 'D:\Sources\project\Project.API\Views\Home\favicon.ico'

because the file wasn't copied / generated.
I would like to be able to deactivate these errors (or turn them to simple warnings) with an option. These error can be distracting, bringing attention where it is not needed.

Thanks.

**Comment by aleksei0807** [comment]
I add this functionality in the latest release.
